version: '3.8'

services:
  moosaic-render-queue-consumer:
    container_name: moosaic-render-queue-consumer
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=consumer
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - net
  moosaic-render-queue-filler:
    container_name: moosaic-render-queue-filler
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=filler
    env_file:
      - ./.env
    networks:
      - net
  moosaic-render-queue:
    image: rabbitmq:3-management
    container_name: moosaic-render-queue
    ports:
      - "15672:15672"
    env_file:
      - ./.env
    networks:
      - net
  networks:
    net:
      driver: bridge